### ISSUE TITLE
Public API: eosio.token::EOS returns empty

### ISSUE THREAD

**Issue by ghost** [DEXEOS/dexeos-api-public#3]
Using the Public API, https://api.dexeos.io/v3/token/eosio.token::EOS returns empty json. However, https://api.dexeos.io/v3/token/ returns the full list of EOS tokens including: {"pk":79,"code":"eosio.token","symbol":"EOS","market":"cusd","decimals":4,"name":"EOS","summary":{"high":7.170361,"low":7.170361,"volume":1.5334,"volume_eos":10.9950315574,"percent":10.31,"last_price":7.170361,"last_tx_type":"buy"}},

**Comment by dreson4** [comment]
You should include ``market`` in your query.

If there's no market included the default market is "EOS", you can't have EOS token in EOS market that's why it's not returning any data.

If you want the EOS price in CUSD market for example you can use 
```
https://api.dexeos.io/v3/token/eosio.token::EOS?market=cusd
```
