### ISSUE TITLE
Public API: Duplicate tokens with different pk

### ISSUE THREAD

**Issue by ghost** [DEXEOS/dexeos-api-public#4]
Duplicate code and symbol exist in EOSDEX. API call for code::symbol only returns first found.

Example of duplicate:
{"pk":88,"code":"therealkarma","symbol":"KARMA","market":"cusd","decimals":4,"name":"KARMA",{"pk":18,"code":"therealkarma","symbol":"KARMA","market":"eos","decimals":4,"name":"KARMA",

For KARMA, pk:18 appears to be the active token trading on EOSDEX. However, it is not possible to retrieve pk:18 directly. Must use a script to call all tokens then parse.

**Comment by dreson4** [comment]
That's because you sent the request to `/token` which returns a list of all the tokens available in all markets. 

You can see one it in EOS market and another one is in CUSD market. So it's correct.
